version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks: 
     - cdc  
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    networks: 
     - cdc 
  mongodb:
    image: debezium/example-mongodb:${DEBEZIUM_VERSION}
    hostname: mongodb
    ports:
     - 27017:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz
    networks: 
     - cdc  
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks: 
      - cdc 

  kafka-ui:
    image: provectuslabs/kafka-ui:latest 
    ports:
     - 8000:8080
    environment: 
     - KAFKA_CLUSTERS_0_NAME=local-kafka 
     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    links: 
     - kafka
    networks: 
     - cdc

networks:
    cdc: